// GENERATED by _Kit\sync-kit.ps1 - do not edit by hand.
// Re-run:  .\sync-kit.ps1 -Project Spm
//
// Lists only the namespaces this project owns. Adding a namespace means
// adding the folder under i18n\ and re-running the sync.

import faSpmAccounts from '@/i18n/spm-accounts/fa.json';
import enSpmAccounts from '@/i18n/spm-accounts/en.json';
import faSpmAdjustments from '@/i18n/spm-adjustments/fa.json';
import enSpmAdjustments from '@/i18n/spm-adjustments/en.json';
import faSpmAudit from '@/i18n/spm-audit/fa.json';
import enSpmAudit from '@/i18n/spm-audit/en.json';
import faSpmHealth from '@/i18n/spm-health/fa.json';
import enSpmHealth from '@/i18n/spm-health/en.json';
import faSpmInstruments from '@/i18n/spm-instruments/fa.json';
import enSpmInstruments from '@/i18n/spm-instruments/en.json';
import faSpmLedger from '@/i18n/spm-ledger/fa.json';
import enSpmLedger from '@/i18n/spm-ledger/en.json';
import faSpmOrders from '@/i18n/spm-orders/fa.json';
import enSpmOrders from '@/i18n/spm-orders/en.json';
import faSpmReconciliation from '@/i18n/spm-reconciliation/fa.json';
import enSpmReconciliation from '@/i18n/spm-reconciliation/en.json';
import faSpmRequestDetail from '@/i18n/spm-request-detail/fa.json';
import enSpmRequestDetail from '@/i18n/spm-request-detail/en.json';
import faSpmRequests from '@/i18n/spm-requests/fa.json';
import enSpmRequests from '@/i18n/spm-requests/en.json';
import faSpmResolution from '@/i18n/spm-resolution/fa.json';
import enSpmResolution from '@/i18n/spm-resolution/en.json';
import faSpmSettlements from '@/i18n/spm-settlements/fa.json';
import enSpmSettlements from '@/i18n/spm-settlements/en.json';

export const DOMAIN_NAMESPACES = {
  fa: {
  'spm-accounts': faSpmAccounts,
  'spm-adjustments': faSpmAdjustments,
  'spm-audit': faSpmAudit,
  'spm-health': faSpmHealth,
  'spm-instruments': faSpmInstruments,
  'spm-ledger': faSpmLedger,
  'spm-orders': faSpmOrders,
  'spm-reconciliation': faSpmReconciliation,
  'spm-request-detail': faSpmRequestDetail,
  'spm-requests': faSpmRequests,
  'spm-resolution': faSpmResolution,
  'spm-settlements': faSpmSettlements,
  },
  en: {
  'spm-accounts': enSpmAccounts,
  'spm-adjustments': enSpmAdjustments,
  'spm-audit': enSpmAudit,
  'spm-health': enSpmHealth,
  'spm-instruments': enSpmInstruments,
  'spm-ledger': enSpmLedger,
  'spm-orders': enSpmOrders,
  'spm-reconciliation': enSpmReconciliation,
  'spm-request-detail': enSpmRequestDetail,
  'spm-requests': enSpmRequests,
  'spm-resolution': enSpmResolution,
  'spm-settlements': enSpmSettlements,
  },
} as const;
