// GENERATED by _Kit\sync-kit.ps1 - do not edit by hand.
// Re-run:  .\sync-kit.ps1 -Project Spm
//
// Lists only the namespaces this project owns. Adding a namespace means
// adding the folder under i18n\ and re-running the sync.

import faBrokeragesCommon from '@/i18n/brokerages-common/fa.json';
import enBrokeragesCommon from '@/i18n/brokerages-common/en.json';
import faCompanyDocument from '@/i18n/company-document/fa.json';
import enCompanyDocument from '@/i18n/company-document/en.json';
import faCompanyInformation from '@/i18n/company-information/fa.json';
import enCompanyInformation from '@/i18n/company-information/en.json';
import faCompanyInformationGuide from '@/i18n/company-information-guide/fa.json';
import enCompanyInformationGuide from '@/i18n/company-information-guide/en.json';
import faPersonAccess from '@/i18n/person-access/fa.json';
import enPersonAccess from '@/i18n/person-access/en.json';
import faPersonAddress from '@/i18n/person-address/fa.json';
import enPersonAddress from '@/i18n/person-address/en.json';
import faPersonAsset from '@/i18n/person-asset/fa.json';
import enPersonAsset from '@/i18n/person-asset/en.json';
import faPersonContact from '@/i18n/person-contact/fa.json';
import enPersonContact from '@/i18n/person-contact/en.json';
import faPersonDocument from '@/i18n/person-document/fa.json';
import enPersonDocument from '@/i18n/person-document/en.json';
import faPersonEducation from '@/i18n/person-education/fa.json';
import enPersonEducation from '@/i18n/person-education/en.json';
import faPersonEmployment from '@/i18n/person-employment/fa.json';
import enPersonEmployment from '@/i18n/person-employment/en.json';
import faPersonForm from '@/i18n/person-form/fa.json';
import enPersonForm from '@/i18n/person-form/en.json';
import faPersonNameGrid from '@/i18n/person-name-grid/fa.json';
import enPersonNameGrid from '@/i18n/person-name-grid/en.json';
import faPersonNationality from '@/i18n/person-nationality/fa.json';
import enPersonNationality from '@/i18n/person-nationality/en.json';
import faPersonProfessionalTraining from '@/i18n/person-professional-training/fa.json';
import enPersonProfessionalTraining from '@/i18n/person-professional-training/en.json';
import faPersonRelationship from '@/i18n/person-relationship/fa.json';
import enPersonRelationship from '@/i18n/person-relationship/en.json';
import faPersonSearch from '@/i18n/person-search/fa.json';
import enPersonSearch from '@/i18n/person-search/en.json';
import faPersonSidebar from '@/i18n/person-sidebar/fa.json';
import enPersonSidebar from '@/i18n/person-sidebar/en.json';
import faPersonStatus from '@/i18n/person-status/fa.json';
import enPersonStatus from '@/i18n/person-status/en.json';
import faSpmAccounts from '@/i18n/spm-accounts/fa.json';
import enSpmAccounts from '@/i18n/spm-accounts/en.json';
import faSpmAdjustments from '@/i18n/spm-adjustments/fa.json';
import enSpmAdjustments from '@/i18n/spm-adjustments/en.json';
import faSpmAudit from '@/i18n/spm-audit/fa.json';
import enSpmAudit from '@/i18n/spm-audit/en.json';
import faSpmHealth from '@/i18n/spm-health/fa.json';
import enSpmHealth from '@/i18n/spm-health/en.json';
import faSpmInstruments from '@/i18n/spm-instruments/fa.json';
import enSpmInstruments from '@/i18n/spm-instruments/en.json';
import faSpmLedger from '@/i18n/spm-ledger/fa.json';
import enSpmLedger from '@/i18n/spm-ledger/en.json';
import faSpmOrders from '@/i18n/spm-orders/fa.json';
import enSpmOrders from '@/i18n/spm-orders/en.json';
import faSpmReconciliation from '@/i18n/spm-reconciliation/fa.json';
import enSpmReconciliation from '@/i18n/spm-reconciliation/en.json';
import faSpmRequestDetail from '@/i18n/spm-request-detail/fa.json';
import enSpmRequestDetail from '@/i18n/spm-request-detail/en.json';
import faSpmRequests from '@/i18n/spm-requests/fa.json';
import enSpmRequests from '@/i18n/spm-requests/en.json';
import faSpmResolution from '@/i18n/spm-resolution/fa.json';
import enSpmResolution from '@/i18n/spm-resolution/en.json';
import faSpmSettlements from '@/i18n/spm-settlements/fa.json';
import enSpmSettlements from '@/i18n/spm-settlements/en.json';

export const DOMAIN_NAMESPACES = {
  fa: {
  'brokerages-common': faBrokeragesCommon,
  'company-document': faCompanyDocument,
  'company-information': faCompanyInformation,
  'company-information-guide': faCompanyInformationGuide,
  'person-access': faPersonAccess,
  'person-address': faPersonAddress,
  'person-asset': faPersonAsset,
  'person-contact': faPersonContact,
  'person-document': faPersonDocument,
  'person-education': faPersonEducation,
  'person-employment': faPersonEmployment,
  'person-form': faPersonForm,
  'person-name-grid': faPersonNameGrid,
  'person-nationality': faPersonNationality,
  'person-professional-training': faPersonProfessionalTraining,
  'person-relationship': faPersonRelationship,
  'person-search': faPersonSearch,
  'person-sidebar': faPersonSidebar,
  'person-status': faPersonStatus,
  'spm-accounts': faSpmAccounts,
  'spm-adjustments': faSpmAdjustments,
  'spm-audit': faSpmAudit,
  'spm-health': faSpmHealth,
  'spm-instruments': faSpmInstruments,
  'spm-ledger': faSpmLedger,
  'spm-orders': faSpmOrders,
  'spm-reconciliation': faSpmReconciliation,
  'spm-request-detail': faSpmRequestDetail,
  'spm-requests': faSpmRequests,
  'spm-resolution': faSpmResolution,
  'spm-settlements': faSpmSettlements,
  },
  en: {
  'brokerages-common': enBrokeragesCommon,
  'company-document': enCompanyDocument,
  'company-information': enCompanyInformation,
  'company-information-guide': enCompanyInformationGuide,
  'person-access': enPersonAccess,
  'person-address': enPersonAddress,
  'person-asset': enPersonAsset,
  'person-contact': enPersonContact,
  'person-document': enPersonDocument,
  'person-education': enPersonEducation,
  'person-employment': enPersonEmployment,
  'person-form': enPersonForm,
  'person-name-grid': enPersonNameGrid,
  'person-nationality': enPersonNationality,
  'person-professional-training': enPersonProfessionalTraining,
  'person-relationship': enPersonRelationship,
  'person-search': enPersonSearch,
  'person-sidebar': enPersonSidebar,
  'person-status': enPersonStatus,
  'spm-accounts': enSpmAccounts,
  'spm-adjustments': enSpmAdjustments,
  'spm-audit': enSpmAudit,
  'spm-health': enSpmHealth,
  'spm-instruments': enSpmInstruments,
  'spm-ledger': enSpmLedger,
  'spm-orders': enSpmOrders,
  'spm-reconciliation': enSpmReconciliation,
  'spm-request-detail': enSpmRequestDetail,
  'spm-requests': enSpmRequests,
  'spm-resolution': enSpmResolution,
  'spm-settlements': enSpmSettlements,
  },
} as const;
